permalink: /blog/:categories/:title.html

title: pddds
subtitle: "not dead yet"
url: http://pddds.com
author: Peter Dodds
email: "peter+at+pddds+com"

nav:
    - name: home
      url: /

links:
    - name: github.com/m0tive
      url: "https://github.com/m0tive"
    - name: twitter.com/m0tive
      url: "http://twitter.com/m0tive"

exclude: README.md
