highlighter: true

permalink: /blog/:categories/:title.html

title: pddds
subtitle: "not dead yet"
url: http://pddds.com
author: Peter Dodds
email: "peter+at+pddds+com"

nav:
    - name: home
      url: /

links:
    - name: github
      url: "https://github.com/m0tive"
    - name: twitter
      url: "http://twitter.com/m0tive"
    - name: "peter+at+pddds+com"
      url: "mailto:peter+at+pddds+com"

googleanalytics: "UA-2993227-8"

exclude:
    - README.md
    - "Gemfile*"
    - "*.sh"
