permalink: /blog/:categories/:title.html

title: pddds
subtitle: "not dead yet"
url: http://pddds.com
author: Peter Dodds
email: "peter+at+pddds+com"

nav:
    - name: home
      url: /

exclude: README.md
