highlighter: true

permalink: /blog/:categories/:title.html

title: pddds
subtitle: "new site, coming soon"
url: http://pddds.com
author: Peter Dodds
email: "peter+at+pddds+com"

googleanalytics: "UA-2993227-8"

exclude:
    - README.md
    - "Gemfile*"
    - "*.sh"

keep_files:
    - wip

timezone: Europe/London
