permalink: /blog/:categories/:title.html

title: pddds
subtitle: "Peter Dodds' website"
url: http://pddds.com
author: Peter Dodds
email: "peter+at+pddds+com"

nav:
    - name: home
      url: /
    - name: about
      url: /about.html
    - name: archive
      url: /archive.html

exclude: README.md
