highlighter: true

permalink: /blog/:categories/:year/:month/:title

title: pddds
subtitle: "new site, coming soon"
url: http://pddds.com
author: Peter Dodds
email: "peter+at+pddds+com"

googleanalytics: "UA-2993227-8"

highlighter: rouge

exclude:
    - "_libs"
    - README.md
    - "Gemfile*"
    - "*.sh"

keep_files:
    - wip

timezone: Europe/London

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "base"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"

sass:
    sass_dir: css/_sass
