permalink: /:categories/:title

title: pddds
url: http://pddds.com

nav:
    - name: pddds
      url: /
    - name: about
      url: /about
    - name: work
      url: /work
    - name: blog
      url: /blog

css:
    - /css/main.css
