permalink: /blog/:categories/:title.html

title: pddds
url: http://pddds.com
author: Peter Dodds
email: "peter+at+pddds+com"

nav:
    - name: pddds
      url: /
    - name: about
      url: /about/
    - name: work
      url: /work/
    - name: code
      url: /code/
    - name: blog
      url: /blog/

css:
    - /lib/main.css

copyright:
    - "Copyright &copy; 2001&ndash;10 <a href=\"mailto:peter+at+pddds+com\">Peter Dodds</a>."

exclude: README.md
