permalink: /:categories/:title

title: pddds
url: http://pddds.com

nav:
    - name: pddds
      url: /
    - name: about
      url: /about.html
    - name: work
      url: /work.html
    - name: code
      url: /code.html
    - name: blog
      url: /blog.html

css:
    - /lib/main.css
